<?php
/**
 * Copyright © 2016 MageWorkshop. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block MageWorkshop\ShoppingCartNotifications\Block\Notifications */
?>

<script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout, #product_addtocart_form, #wishlist-view-form, .action.tocart": {
            "mageWorkshopShoppingCartNotifications": {
                "loaderEnabled"              : <?php /* @escapeNotVerified */ echo $block->getLoaderEnabled(); ?>,
                "notificationsEnabled"       : <?php /* @escapeNotVerified */ echo $block->getNotificationsEnabled(); ?>,
                "autoHideDelay"              : <?php /* @escapeNotVerified */ echo $block->getAutoHideDelay(); ?>,
                "disableDefaultNotification" : <?php /* @escapeNotVerified */ echo $block->getDefaultNotificationIsDisabled(); ?>
            }
        }
    }
</script>